#ifndef commands_h
#define commands_h

// ACTION COMMANDS
#define QUIT_COMMAND "QUIT"

// ARITMETICS COMMANDS
#define SUMA_COMMAND "+"
#define RESTA_COMMAND "-"
#define MULTIPLICAR_COMMAND "*"
#define MULTIPLICAR_COMMAND_ALTERNATIVE "x"
#define DIVIDIR_COMMAND "/"

// ESPECIAL COMMANDS
#define NO_COMMAND "NO_COMMAND"
#define COMMAND_ERROR "COMMAND_ERROR"
#define ADD_NUMERIC_VALUE "ADD_NUMERIC_VALUE"

// EASTER EGG
#define IMPOSIBLE_COMMAND "IMPOSIBLE_COMMAND"

#endif
