#ifndef commands_h
#define commands_h

// ACTION COMMANDS
#define QUIT_COMMAND "QUIT"

// ARITMETICS COMMANDS
#define SUMA_COMMAND "+"
#define RESTA_COMMAND "-"
#define MULTIPLICAR_COMMAND "*"
#define MULTIPLICAR_COMMAND_ALTERNATIVE "x"
#define DIVIDIR_COMMAND "/"
#define RAIZ_COMMAND "SQRT"
#define POTENCIA_COMMAND "^"
#define FACTORIAL_COMMAND "!"
#define CIMA_COMMAND "RCL"
#define DISPLAY_COMMAND "DSP"
#define CLEAR_COMMAND "CLR"
#define SENO_COMMAND "SIN"
#define COSENO_COMMAND "COS"
#define TANGENTE_COMMAND "TAN"
#define LOGARITMO_COMMAND "LOG"
#define ARCSENO_COMMAND "ARCSIN"
#define ARCCOSENO_COMMAND "ARCCOS"
#define ARCTAN_COMMAND "ARCTAN"
#define SWAP_COMMAND "SWP"

// ESPECIAL COMMANDS
#define NO_COMMAND "NO_COMMAND"
#define COMMAND_ERROR "COMMAND_ERROR"
#define ADD_NUMERIC_VALUE "ADD_NUMERIC_VALUE"

// MEMORY COMMANDS
#define MEMORY_STORE_COMMAND "STR"
#define MEMORY_RECALL_COMMAND "MRCL"
#define MEMORY_SUMA_COMMAND "S+"
#define MEMORY_RESTA_COMMAND "S-"

// NUMERIC COMMANDS
#define DEC_BINARY_COMMAND "BINARY"
#define DEC_OCTAL_COMMAND "OCTAL"
#define DEC_HEXA_COMMAND "HEXA"
#define BINARY_DECIMAL_COMMAND "DECIMAL"
#define OCTAL_DECIMAL_COMMAND "OCTALTODECIMAL"

// EASTER EGG
#define IMPOSIBLE_COMMAND "IMPOSIBLE_COMMAND"

#endif
