#ifndef commands_h
#define commands_h

// ACTION COMMANDS
#define QUIT_COMMAND "QUIT"

// ARITMETICS COMMANDS
#define SUMA_COMMAND "+"
#define MULTIPLICAR_COMMAND "*"
#define MULTIPLICAR_COMMAND_ALTERNATIVE "x"
#define SENO_COMMAND "SIN"
#define COSENO_COMMAND "COS"
#define TANGENTE_COMMAND "TAN"
#define LOGARITMO_COMMAND "LOG"
#define ARCSENO_COMMAND "ARCSIN"
#define ARCCOSENO_COMMAND "ARCCOS"
#define ARCTAN_COMMAND "ARCTAN"
#define SWAP_COMMAND "SWP"


// ESPECIAL COMMANDS
#define NO_COMMAND "NO_COMMAND"
#define COMMAND_ERROR "COMMAND_ERROR"
#define ADD_NUMERIC_VALUE "ADD_NUMERIC_VALUE"

// EASTER EGG
#define IMPOSIBLE_COMMAND "IMPOSIBLE_COMMAND"

#endif
